"""
Pydantic schemas shared across Onyx modules.

These are the data contracts between:
  - the LLM layer (raw JSON outputs)
  - the storage layer (what gets persisted)
  - the runtime layer (what gets returned to callers)

Every external boundary is validated here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, Optional, cast

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Enums (as literals for compactness)
# ---------------------------------------------------------------------------

KnowledgeType = Literal["fact", "procedure", "code", "tool", "failure"]
DedupeAction = Literal["add", "update", "duplicate", "conflict"]


# ---------------------------------------------------------------------------
# Skill specification — generated by the LLM during bootstrap
# ---------------------------------------------------------------------------

class SkillSpec(BaseModel):
    """Structured plan for a skill, produced by the spec-builder prompt."""

    name: str
    description: str = ""
    subtopics: list[str] = Field(default_factory=list)
    tools: list[str] = Field(default_factory=list)
    keywords: list[str] = Field(default_factory=list)
    success_criteria: list[str] = Field(default_factory=list)
    legal_notes: str = ""

    @field_validator("name")
    @classmethod
    def _name_non_empty(cls, v: str) -> str:
        v = (v or "").strip()
        if not v:
            raise ValueError("skill name is required")
        return v

    @field_validator("subtopics", "tools", "keywords", "success_criteria")
    @classmethod
    def _clean_list(cls, v: list[str]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for item in v or []:
            item = str(item).strip()
            if item and item.lower() not in seen:
                seen.add(item.lower())
                out.append(item)
        return out


# ---------------------------------------------------------------------------
# Knowledge entry — the atomic unit stored in a skill DB
# ---------------------------------------------------------------------------

class KnowledgeEntry(BaseModel):
    """A single piece of knowledge extracted from a web source."""

    title: str
    type: KnowledgeType = "fact"
    content: str
    source_url: str = ""
    source_type: str = "web"
    confidence: float = 0.7
    tags: list[str] = Field(default_factory=list)

    @field_validator("type", mode="before")
    @classmethod
    def _fallback_type(cls, v: Any) -> KnowledgeType:
        allowed_types = {"fact", "procedure", "code", "tool", "failure"}
        if isinstance(v, str):
            v = v.strip().lower()
            if v in allowed_types:
                return cast(KnowledgeType, v)
        return "fact"

    @field_validator("title")
    @classmethod
    def _title_ok(cls, v: str) -> str:
        v = (v or "").strip() or "Untitled"
        return v[:200]

    @field_validator("content")
    @classmethod
    def _content_min(cls, v: str) -> str:
        v = (v or "").strip()
        if len(v) < 40:
            raise ValueError("content too short (<40 chars)")
        return v

    @field_validator("confidence")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        return max(0.0, min(1.0, float(v)))

    @field_validator("tags")
    @classmethod
    def _clean_tags(cls, v: list[str]) -> list[str]:
        return [str(t).strip() for t in (v or []) if str(t).strip()][:20]


# ---------------------------------------------------------------------------
# Runtime planning
# ---------------------------------------------------------------------------

class RuntimePlan(BaseModel):
    """Plan produced by the runtime planner prompt."""

    steps: list[str] = Field(default_factory=list)
    needs_code: bool = False
    needs_web: bool = False
    notes: str = ""

    @field_validator("steps")
    @classmethod
    def _clean_steps(cls, v: list[str]) -> list[str]:
        return [str(s).strip() for s in (v or []) if str(s).strip()][:20]


# ---------------------------------------------------------------------------
# Model builder
# ---------------------------------------------------------------------------

class TrainingPlan(BaseModel):
    """Plan produced by the training planner prompt."""

    dataset_name: str = ""
    dataset_url: str = ""
    approach: str = ""
    library: Literal["sklearn", "transformers", "pytorch"] = "sklearn"
    train_code: str = ""

    @field_validator("train_code")
    @classmethod
    def _code_non_empty(cls, v: str) -> str:
        v = (v or "").strip()
        if not v:
            raise ValueError("train_code is required")
        return v


# ---------------------------------------------------------------------------
# Internal dataclasses (not serialized to users)
# ---------------------------------------------------------------------------

@dataclass
class SkillRecord:
    """A row in the skill registry table."""

    skill_id: str
    name: str
    description: str
    tools: list[str]
    created_at: str
    updated_at: str
    entry_count: int = 0
    spec: dict[str, Any] = field(default_factory=dict)


@dataclass
class Source:
    """A web search result."""

    title: str
    url: str
    snippet: str = ""


@dataclass
class RuntimeResult:
    """The final output of a runtime task."""

    answer: str
    plan: dict[str, Any]
    code_output: str
    gap: dict[str, Any]
    new_entries: int
    context_used: int


__all__ = [
    "KnowledgeType",
    "DedupeAction",
    "SkillSpec",
    "KnowledgeEntry",
    "RuntimePlan",
    "TrainingPlan",
    "SkillRecord",
    "Source",
    "RuntimeResult",
]
